[package]
authors = ["Dan Nguyen <pedantic@gmail.com>"]
edition = "2021"
name = "chunk-perf"
version = "0.1.0"

[dependencies]

[dev-dependencies]
criterion = "0.5"

[[bench]]
harness = false
name = "split"
