[package]
authors = ["Dan Nguyen <pedantic@gmail.com>"]
edition = "2021"
name = "insert"
version = "0.1.0"

[dependencies]
linked-list = "0.0.3"

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"

[[bench]]
harness = false
name = "main"
