name:                fusion
version:             0.1.0.0
github:              "pedantic79/fusion"
license:             BSD3
author:              "Daniel Nguyen"
maintainer:          "pedantic@gmail.com"
copyright:           "Copyright (c) 2018 Daniel Nguyen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            None

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pedantic79/fusion#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  fusion-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fusion
    - criterion

tests:
  fusion-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fusion
    - tasty
    - tasty-quickcheck
