[package]
authors = ["Dan Nguyen <pedantic@gmail.com>"]
edition = "2018"
name = "json"
version = "0.1.0"

[dependencies]
env_logger = "0.10"
log = "0.4.6"
serde = "1.0.92"
serde_derive = "1.0.92"
serde_json = "1.0.39"
